project:
  type: website
  output-dir: docs

website:
  title: "website6"
  navbar:
    left:
      - href: index.qmd
        text: Resume
      - href: about.qmd
        text: Presentation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



