project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Resume
      - href: Presentation.qmd
        text: Presentation
      - href: InteractiePlots.qmd
        text: Interactive Plots
      - href: ParamMarkdown.qmd
        text: Interactive Plots

format:
  html:
    theme: lux
    css: styles.css
    toc: true



